pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('Deploy to PROD Guild') {
            when {
                branch 'master'
            }
            steps {
                withCredentials(
                    [
                        string(credentialsId: 'WALL_E_PROD_DISCORD_BOT_TOKEN', variable: 'WALL_E_PROD_DISCORD_BOT_TOKEN'),
                        string(credentialsId: 'WOLFRAM_API_TOKEN', variable: 'WOLFRAM_API_TOKEN'),
                        string(credentialsId: 'MEE6_AUTHORIZATION', variable: 'MEE6_AUTHORIZATION'),
                        string(credentialsId: 'POSTGRES_PASSWORD', variable: 'POSTGRES_PASSWORD'),
                        string(credentialsId: 'WALL_E_DB_PASSWORD', variable: 'WALL_E_DB_PASSWORD'),
                        usernamePassword(credentialsId: 'docker-hub-perms',passwordVariable: 'DOCKER_HUB_PASSWORD',usernameVariable: 'DOCKER_HUB_USER_NAME')
                    ]
                ) {
                    sh('''
export DISCORD_NOTIFICATION_MESSAGE_FILE=OUTPUT;
export COMPOSE_PROJECT_NAME=PRODUCTION_MASTER;

./CI/deploy.sh;
                    ''')
                }
            }
        }
    }
    post {
        always {
            script {
                if (fileExists('OUTPUT')){
                    summary=readFile('OUTPUT').trim()
                    theTitle = "ISSUE DETECTED"
                    status = false
                }else{
                    if (currentBuild.currentResult == "SUCCESS"){
                        theTitle = "SUCCESS"
                        summary = "No issues detected"
                        status = true
                    }else{
                        theTitle = "ISSUE DETECTED"
                        summary = "Please look at Jenkins for more info"
                        status = false
                    }
                }

                withCredentials([string(credentialsId: 'DISCORD_WEBHOOK', variable: 'WEBHOOKURL')]) {
                    discordSend description: "Branch or PR Name: " + BRANCH_NAME + '\n' + summary, footer: env.GIT_COMMIT, link: env.BUILD_URL, successful: status, title: theTitle, webhookURL: '$WEBHOOKURL'
                }
            }
            cleanWs(
            cleanWhenAborted: true,
            cleanWhenFailure: true,
            cleanWhenNotBuilt: false,
            cleanWhenSuccess: true,
            cleanWhenUnstable: true,
            deleteDirs: true,
            disableDeferredWipeout: true
        )
        }
    }
}